name: little_light
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
### MUST HAVE 2 digits on last part
version: 1.7.32+107032

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  tinycolor: 1.0.2
  shared_preferences: 0.5.1+2
  archive: any
  sqflite: 1.1.3 
  http: ^0.12.0+2 
  path_provider: ^1.1.2
  uni_links: ^0.2.0
  font_awesome_flutter: ^8.4.0
  bungie_api: 12.8.1
  flutter_linkify: 3.1.0

  shimmer: 1.0.0
  flutter_staggered_grid_view: ^0.3.0
  timeago: ^2.0.14
  firebase_crashlytics: 0.1.3+3
  firebase_analytics: 5.0.16
  flutter_dotenv: 2.0.1 
  url_launcher: ^5.0.2
  screen: ^0.0.5
  package_info: 0.4.0+2
  device_info: 0.4.0+1
  flutter_range_slider: ^1.1.0
  uuid: 2.0.0
  flutter_advanced_networkimage: 0.7.0
  launch_review: 2.0.0
  esys_flutter_share: 1.0.2
  drag_list: 1.0.7
  json_annotation:

  speech_bubble: ^0.0.5
  
dev_dependencies:
  build_runner: 
  json_serializable: 
  intl_translation: ^0.17.1
  flutter_test:
    sdk: flutter
    
dependency_overrides:
    flutter_svg: 0.18.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/_env
    - assets/imgs/
    - assets/imgs/flags/
    - assets/subclasses/
    - assets/anim/
    - assets/i18n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family:  LittleLightIcons
      fonts:
      - asset: fonts/LittleLightIcons.ttf
    # - family: NeueHaasDisplay
      # fonts:
      # - asset: fonts/NeueHaasDisplay-Thin.ttf
      #   weight: 300
      # - asset: fonts/NeueHaasDisplay-ThinItalic.ttf
      #   weight: 300
      #   style: italic
      # - asset: fonts/NeueHaasDisplay-Roman.ttf
      #   weight: 500
      # - asset: fonts/NeueHaasDisplay-Medium.ttf
      #   weight: 700
      # - asset: fonts/NeueHaasDisplay-Bold.ttf
      #   weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
# 